POST /clients/ordersの実装
yusuke1526/yumemi_intern pull request #1
Opened 2022-10-07 09:22 UTC by yusuke1526

値に不正があったときが怖いので、DB登録前に全て値をチェックするようにしました。

たまに[api/views.py](https://github.com/yusuke1526/yumemi_intern/compare/post_/clients/orders?expand=1#diff-7fb412808754eb12ee1b172c34c44eb9ce58b3bba43d62ffcb986ad7917588a8)の72行目のテーブルオブジェクトを持ってくる箇所で遅くなるのが気になっています。

よろしくお願いします。

2022-10-11 01:47 UTC, Tuitsuchi commented
DB登録前に全ての値をチェックということで、多分validation処理をしたいんだなと仮定してレビューしますね。
大体REST APIをFWで作るときはvalidationの処理機能がFWに備わっているので、それを使うことが多く、クラスなども分けて書くことが殆どです。
公式のvalidationに関するDOCは[こちら](https://docs.djangoproject.com/ja/4.1/ref/validators/)
さて、その上で今回は時間がなく、全てviewsに書いてしまうことにしましょう。
その上で、validationに関する処理は別関数に切り出してしまうのがいいかなと思います。その方がのちに改修や仕様把握がやりやすいので

2022-10-11 02:00 UTC, Tuitsuchi commented on api/views.py
> +        order_detail['item'] = item
こちらが時折重くなるということでしたので、少し見てみました。
多分itemのテーブルから一つずつ検索をかけていて、そのdeserializeのオーバヘッドが重くなってるのではないかな、と考えました。
なので、このチェックを一度の検索で終えられるような処理を考えるのがいいかなと考えます。
[こちら](https://docs.djangoproject.com/ja/4.1/ref/models/querysets/#in)をみて実装してみると良いかと思われます。
where inの条件で検索、結果のヒットレコード数を期待値比べて一致していればOKみたいな処理にすればある程度の処理工程短縮が見込めると思います

2022-10-11 02:00 UTC, Tuitsuchi commented on api/views.py
> +        order_details_objects[i] = order_detail
この辺りも同じ発想でいけるかもしれないですね。
itemとの関係を考慮する必要があるので、その辺のことも考えられると尚よしです。

2022-10-12 02:31 UTC, yumemi-kkawai requested changes

2022-10-12 02:31 UTC, yumemi-kkawai commented on api/views.py
> +import json
全体的な話になりますが、責務を分割した方がいいでしょう。
複数の機能を追加していくと、このままだとviewsは肥大化する一方です。テストも書けなくなると思います。

viewsの分割とかでググればいくつかの例が出てきますね。いずれかを参考にしてみてください。
https://jpn.itlibra.com/article?id=20936

例の通り、1ファイルが1エンドポイントとなるような構成だとスッキリしますね。

2022-10-12 02:32 UTC, yumemi-kkawai commented on api/views.py
> +        # OrderDetailレコードを作成
これはできたらやってみてくださいと言う指摘です。

我々が書く実際のアプリケーションでは、いわゆるMVCモデルにおけるCのレイヤーをいくつかに分割します。
例えば次のような感じです

- ビジネスロジックを書くところ(usecase)
- データを取得、操作するところ(repository)

今回のケースだとVCが一つのファイルになっていますが、実際の現場ではこのようには書きません。
V, UseCase, Repository と最低でも3つに分割されるでしょう。

一旦はエンドポイントごとの分割をしてもらった上で、インターン後半で時間が余ればリファクタリングしてみましょう。

2022-10-12 09:40 UTC, yusuke1526 commented
確認したところ修正によってクエリ実行回数が23→7になってました。
一括処理にしたのでitemやoptionの数の影響を受けないと思います。

2022-10-12 09:43 UTC, yumemi-kkawai commented on api/migrations/0001_initial.py
> +# Generated by Django 4.1.2 on 2022-10-06 08:08
マイグレーションとして分割いいね！

2022-10-12 09:48 UTC, yumemi-kkawai requested changes

2022-10-12 09:48 UTC, yumemi-kkawai commented on api/views/orders.py
> +    if len(item_ids) != len(items_queryset):
item_id の重複は考慮していますか？
同一 item_id でオプション違いのオーダーが複数あった場合、エラーになってしまいそうです。

存在チェックする時の item_ids はあらかじめ重複の排除をしておくと良さそう。

2022-10-12 09:48 UTC, yumemi-kkawai commented on api/views/orders.py
> +    if len(option_ids) != len(options_queryset):
ここも重複考えたほうが良さそう

2022-10-12 09:55 UTC, yusuke1526 commented on api/views/orders.py
> +    if len(item_ids) != len(items_queryset):
どこでエラーが起こる想定でしょうか？
item_idsはsetにしてあるのでitem_ids内では重複はないと思いますが。

2022-10-12 10:53 UTC, yumemi-kkawai approved these changes
LGTM!

2022-10-13 05:11 UTC, merged